config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get 'checklogin'

    end
    member do
      get 'auth'
      get 'saveauth'
    end
  end
  resources :compans
  resources :suppliers
  resources :raws
  resources :inrawdepots do
    collection do
      get 'getdata'
      get 'getsupplier'
      get 'getraw'
      get 'getrawbyid'
      get 'changeinrawdetail'
    end
  end

  resources :newraws
  resources :innewraws do
    collection do
      get 'getsupplier'
      get 'getdata'
      get 'getraw'
      get 'changeinrawdetail'
      get 'deleteinrawdetail'
    end
  end
  resources :newdepots do

  end
  resources :preorders do
    collection do
      get 'getdata'
      get 'getpreraw'
      get 'changeinrawdetail'
      get 'deleteinrawdetail'
      get 'work'
      get 'getcooperuser'
      get 'getcumtomerbyid'
      get 'getrawbyid'
    end
    member do
      get 'dowork'
      get 'work'
    end
  end

  resources :rawdepots
  resources :inrawdepotrecords do
    collection do
      get 'getdata'
    end
  end
  resources :inworkdepots do
    collection do
      get 'getdata'
      get 'getsupplier'
      get 'getraw'
      get 'getrawbyid'
      get 'changeinworkdetail'
    end
  end
  resources :inworkdepotdetails do
    collection do
      get 'getdata'
    end
  end
  resources :inworkdepotrecords do
    collection do
      get 'getdata'
    end
  end
  resources :workdepots
  resources :sales do
    collection do
      get 'getdata'
      get 'getraw'
    end
  end
  resources :saledepots
  resources :insaledepots do
    collection do
      get 'getdata'
      get 'getsale'
      get 'getsalebyid'
      get 'changeinsaledetail'
      get 'getwork'
      get 'getworkbyid'
    end
  end
  resources :insaledepotrecords do
    collection do
      get 'getdata'
    end
  end
  resources :goods
  resources :gooddepots
  resources :ingooddepots do
    collection do
      get 'getdata'
      get 'getgood'
      get 'getgoodbyid'
      get 'changeingooddetail'
    end
  end
  resources :ingooddepotrecords do
    collection do
      get 'getdata'
    end
  end
  resources :customers
  resources :reserves do
    collection do
      get 'getdata'
      get 'getcustomer'
      get 'getsale'
      get 'getsalebyid'
      get 'changereserve'
      get 'trans'
    end
  end
  resources :reservedetails
  resources :saleres do
    collection do
      get 'getdata'
      get 'getcustomer'
      get 'getsale'
      get 'getsalebyid'
      get 'changesalere'
    end
  end
  resources :saleredetails
  resources :workattchs
  resources :workatts
  resources :coopers do
    resources :cooperusers
  end
  resources :preraws

  resources :newworks do
    collection do
      get 'getdata'
      get 'getpreraw'
      get 'changenewworkdetail'
      get 'deleteinrawdetail'
      get 'work'
      get 'getcooperuser'
      get 'getrawbyid'
      get 'gettotal'
      get 'getcumtomerbyid'
      get 'group'
      get 'saveshape'
    end
    member do
      get 'worklian'
      get 'sett'
    end
  end
  resources :workrecords
  resources :designers
  resources :fiters
  resources :borrowgoods do
    collection do
      get 'getdata'
      get 'getgood'
      get 'getgoodbyid'
      get 'changeingooddetail'
    end
  end
  resources :returngoods do
    collection do
      get 'getdata'
      get 'getgood'
      get 'getgoodbyid'
      get 'changeingooddetail'
    end
  end
  resources :prefixorders
  resources :workdayrepots do
    collection do
      get 'getmonth'
      get 'getyear'
    end
  end
  resources :paymenttypes
  resources :preorderanalyses
  resources :customerpayments
  resources :colorlibs

end

app/models/colorlib.rb
class Colorlib < ApplicationRecord
end

app/models/compan.rb
class Compan < ApplicationRecord
end

app/models/cooper.rb
class Cooper < ApplicationRecord
  has_many :cooperusers
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :payments
end

app/models/designer.rb
class Designer < ApplicationRecord
end

app/models/fiter.rb
class Fiter < ApplicationRecord
end

app/models/good.rb
class Good < ApplicationRecord

  has_many :ingooddepotdetails
  has_many :gooddepots
has_many :borrowdetails
  has_many :returngooddetails

end

app/models/innewraw.rb
class Innewraw < ApplicationRecord
  has_many :innewdepotdetails
end

app/models/newdepot.rb
class Newdepot < ApplicationRecord
  has_many :newdepotdetails
end

app/models/newraw.rb
class Newraw < ApplicationRecord
  has_many :newrawspecs
  has_many :newworkdetails
end

app/models/newwork.rb
class Newwork < ApplicationRecord
  has_many :newworkdetails
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :customer
end

app/models/preorder.rb
class Preorder < ApplicationRecord
  has_many :preorderdetails
end

app/models/preraw.rb
class Preraw < ApplicationRecord

end

app/models/raw.rb
class Raw < ApplicationRecord
  has_many :inrawdepotdetails
  has_many :rawdepots
  has_many :inrawdepots
  has_many :inworkdepotdetails

  has_many :saledetails
end

app/models/reserve.rb
class Reserve < ApplicationRecord
  has_many :reservedetails
end

app/models/sale.rb
class Sale < ApplicationRecord
  has_many :saledepots
  has_many :insaledepotdetails
  has_many :reservedetails
  has_many :saleredetails
  has_many :saledetails
end

app/models/salere.rb
class Salere < ApplicationRecord
  has_many :saleredetails
end

app/models/shape.rb
class Shape < ApplicationRecord
  belongs_to :newworkdetail
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/models/workatt.rb
class Workatt < ApplicationRecord
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController

  before_action :set_designer, only: [:show, :edit, :update, :destroy]
  def index
    @designers = Designer.all
  end

  def edit

  end

  def new
    @designer = Designer.new
  end

  def create
    @designer = Designer.new(designer_params)
    respond_to do |format|
      if @designer.save
        #@good.pinyin = safestring(HanziToPinyin.hanzi_to_pinyin(@good.name))
        #@good.save
        format.html { redirect_to designers_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @designer.update(designer_params)
        #@good.pinyin = safestring(HanziToPinyin.hanzi_to_pinyin(@good.name))
        #@good.save
        format.html { redirect_to designers_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @designer }
      else
        format.html { render :edit }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end

  end


  def destroy
    @designer.destroy
    respond_to do |format|
      format.html { redirect_to designers_path, notice: '删除成功' }
      format.json { head :no_content }
    end
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_designer
    @designer = Designer.find(params[:id])
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def designer_params
    params.require(:designer).permit(:name, :tel)
  end

  def safestring(str)
    mystr =""
    str.each_byte  do |byte|
      if (byte > 47 && byte < 58) || (byte > 96 && byte < 123)
        mystr+=byte.chr
      end
    end
    return mystr
  end

end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/views/designers/_form.html.erb
<script>
    $(document).ready(function(){


    });

</script>
<div class="col-md-12 ibox ibox-content">
  <div class="ibox-content form-horizontal m-t">
    <input type="hidden" id="teminterestid">
    <div class="form-group">
      <%= form_for(@designer,:html => {:class=>'form-horizontal m-t',:multipart => true,:id=>'userform'}) do |f| %>
          <div class="form-group">
            <label class="col-sm-3 control-label">姓名：</label>
            <div class="col-sm-5">
              <%= f.text_field :name,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">电话：</label>
            <div class="col-sm-5">
              <%= f.text_field :tel,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label"></label>
            <div class="col-sm-5 text-right">
              <%= f.submit '确定',class: "btn btn-w-m btn-primary ",id:'smt' %>&nbsp;<%= link_to "返回",designers_path,class: "btn btn-w-m btn-primary " %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/designers/edit.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>编辑设计师</h3>
    </div>
    <%= render 'form', customer: @cumtomer %>
  </div>
</div>
<%=render 'layerend' %>

app/views/designers/index.html.erb
<%= render 'layerbegin' %>
<script>
    $(document).ready(function(){

    });
</script>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h5>设计师管理</h5>
      <div class="ibox-tools col-sm-3" style="margin-top: -5px;">
        <div class="input-group">
          <input type="text" id="search" class="input-sm form-control"> <span class="input-group-btn">
          <button type="button" id="searchbtn" class="btn btn-sm btn-primary"> 搜索</button> </span>
        </div>
      </div>
    </div>
    <div class="ibox-content">
      <table class="table table-hover table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">姓名</th>
          <th class="text-center">电话</th>
          <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <% @designers.each do |designer| %>
            <tr>
              <td>
                <%= designer.name %>
              </td>
              <td>
                <%= designer.tel %>
              </td>
              <td>
                <%= link_to '编辑',edit_designer_path(designer),class:'fa fa-edit' %>&nbsp;
                <%= link_to ' 删除', designer, method: :delete, data: { confirm: '确认删除?' },class:'fa fa-trash' %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to "新增",new_designer_path,class: "btn btn-w-m btn-primary pull-right" %>
      <br/>
    </div>
  </div>
</div>

<%=render 'layerend' %>

app/views/designers/new.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>新增设计师</h3>
    </div>
    <%= render 'form', designer: @designer %>
  </div>
</div>
<%=render 'layerend' %>