config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get 'checklogin'

    end
    member do
      get 'auth'
      get 'saveauth'
    end
  end
  resources :compans
  resources :suppliers
  resources :raws
  resources :inrawdepots do
    collection do
      get 'getdata'
      get 'getsupplier'
      get 'getraw'
      get 'getrawbyid'
      get 'changeinrawdetail'
    end
  end

  resources :newraws
  resources :innewraws do
    collection do
      get 'getsupplier'
      get 'getdata'
      get 'getraw'
      get 'changeinrawdetail'
      get 'deleteinrawdetail'
    end
  end
  resources :newdepots do

  end
  resources :preorders do
    collection do
      get 'getdata'
      get 'getpreraw'
      get 'changeinrawdetail'
      get 'deleteinrawdetail'
      get 'work'
      get 'getcooperuser'
      get 'getcumtomerbyid'
      get 'getrawbyid'
    end
    member do
      get 'dowork'
      get 'work'
    end
  end

  resources :rawdepots
  resources :inrawdepotrecords do
    collection do
      get 'getdata'
    end
  end
  resources :inworkdepots do
    collection do
      get 'getdata'
      get 'getsupplier'
      get 'getraw'
      get 'getrawbyid'
      get 'changeinworkdetail'
    end
  end
  resources :inworkdepotdetails do
    collection do
      get 'getdata'
    end
  end
  resources :inworkdepotrecords do
    collection do
      get 'getdata'
    end
  end
  resources :workdepots
  resources :sales do
    collection do
      get 'getdata'
      get 'getraw'
    end
  end
  resources :saledepots
  resources :insaledepots do
    collection do
      get 'getdata'
      get 'getsale'
      get 'getsalebyid'
      get 'changeinsaledetail'
      get 'getwork'
      get 'getworkbyid'
    end
  end
  resources :insaledepotrecords do
    collection do
      get 'getdata'
    end
  end
  resources :goods
  resources :gooddepots
  resources :ingooddepots do
    collection do
      get 'getdata'
      get 'getgood'
      get 'getgoodbyid'
      get 'changeingooddetail'
    end
  end
  resources :ingooddepotrecords do
    collection do
      get 'getdata'
    end
  end
  resources :customers
  resources :reserves do
    collection do
      get 'getdata'
      get 'getcustomer'
      get 'getsale'
      get 'getsalebyid'
      get 'changereserve'
      get 'trans'
    end
  end
  resources :reservedetails
  resources :saleres do
    collection do
      get 'getdata'
      get 'getcustomer'
      get 'getsale'
      get 'getsalebyid'
      get 'changesalere'
    end
  end
  resources :saleredetails
  resources :workattchs
  resources :workatts
  resources :coopers do
    resources :cooperusers
  end
  resources :preraws

  resources :newworks do
    collection do
      get 'getdata'
      get 'getpreraw'
      get 'changenewworkdetail'
      get 'deleteinrawdetail'
      get 'work'
      get 'getcooperuser'
      get 'getrawbyid'
      get 'gettotal'
      get 'getcumtomerbyid'
      get 'group'
      get 'saveshape'
    end
    member do
      get 'worklian'
      get 'sett'
    end
  end
  resources :workrecords
  resources :designers
  resources :fiters
  resources :borrowgoods do
    collection do
      get 'getdata'
      get 'getgood'
      get 'getgoodbyid'
      get 'changeingooddetail'
    end
  end
  resources :returngoods do
    collection do
      get 'getdata'
      get 'getgood'
      get 'getgoodbyid'
      get 'changeingooddetail'
    end
  end
  resources :prefixorders
  resources :workdayrepots do
    collection do
      get 'getmonth'
      get 'getyear'
    end
  end
  resources :paymenttypes
  resources :preorderanalyses
  resources :customerpayments
  resources :colorlibs

end

app/models/sale.rb
class Sale < ApplicationRecord
  has_many :saledepots
  has_many :insaledepotdetails
  has_many :reservedetails
  has_many :saleredetails
  has_many :saledetails
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  def index
    @sales = Sale.all
    @preorders = Preorder.where('isnew = 0').paginate(:page => params[:page], :per_page => 20)
    if params[:search]
      customer = Customer.where('name like ?',"%#{params[:search]}%")
      @preorders = Preorder.where('(ordernumber like ? or customer_id in (?)) and isnew = 0',"%#{params[:search]}%",customer.ids).paginate(:page => params[:page], :per_page => 20)
    end
  end

  def edit

  end

  def new
    @sale = Sale.create(isnew:1)
    redirect_to edit_sale_path(@sale)
  end

  def create
    @sale = Sale.new(sale_params)
    respond_to do |format|
      if @sale.save
        @sale.pinyin = safestring(HanziToPinyin.hanzi_to_pinyin(@sale.name))
        @sale.save
        format.html { redirect_to sales_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @sale.update(sale_params)
        @sale.pinyin = safestring(HanziToPinyin.hanzi_to_pinyin(@sale.name))
        @sale.save
        format.html { redirect_to sales_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_path, notice: '删除成功' }
      format.json { head :no_content }
    end
  end

  class Saledetailclass
    attr :id,true
    attr :raw,true
    attr :spec,true
    attr :unit,true
    attr :cost,true
    attr :price,true
    attr :number,true
  end

  def getdata
    @saledetails = Sale.find(params[:saleid]).saledetails
    saledetailarr = Array.new
    @saledetails.each do |f|
      saledetailcla = Saledetailclass.new
      saledetailcla.id = f.id
      saledetailcla.raw = f.raw.name
      saledetailcla.spec = f.raw.spec
      saledetailcla.unit = f.raw.unit
      saledetailcla.cost = f.raw.price
      saledetailcla.number = f.number
      saledetailcla.sum = f.sum
      saledetailarr.push saledetailcla
    end
    render json:saledetailarr
  end

  class Rawclass
    attr :id,true
    attr :pinyin,true
    attr :name,true
    attr :spec,true
    attr :depotnumber,true
    attr :unit,true
    attr :price,true
  end

  def getraw
    raws = Raw.all
    rawarr = Array.new
    raws.each do |f|
      rawcla = Rawclass.new
      rawcla.id = f.id
      rawcla.pinyin = raw.pinyin
      rawcla.name = raw.name
      rawcla.spec = raw.spec
      #rawcla.depotnumber = f.number
      rawarr.push rawcla
    end
    render json:rawarr
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_sale
    @sale = Sale.find(params[:id])
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def sale_params
    params.require(:sale).permit(:name, :spec, :unit, :price, :cost, :pinyin)
  end

  def safestring(str)
    mystr =""
    str.each_byte  do |byte|
      if (byte > 47 && byte < 58) || (byte > 96 && byte < 123)
        mystr+=byte.chr
      end
    end
    return mystr
  end

end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<script>
  var way='';
    $(document).ready(function(){

        getdata();



        var datalist;
        $.ajax({
            type : 'get',
            async : false,
            url :'../getraw',
            success : function(data) {
                datalist=data;
            }
        });
        suggest(datalist);

        function suggest(data) {
            var testdataBsSuggest = $("#raw_data").bsSuggest(
                    {
                        indexId: 0, indexKey: 1,
                        data: {
                            "value": data
                        }
                    }).on('onSetSelectValue', function (e, keyword) {
              $('#customer_id').val(keyword.id);
            });
        }




        $('#modalsubmit').click(function(){
            $.ajax({
                type : 'get',
                async : false,
                url :'../changesalere',
                data:{
                    way:way,
                    salereid:$('#salereid').val(),
                    saleid:$('#modelid').val(),
                    number:$('#modelnumber').val(),
                    price:$('#modelprice').val(),
                    sum:$('#modelsum').val()
                },
                success : function(json) {
                  getdata();
                  $('#raw_data').val('');
                  $('#modelspec').val('');
                  $('#modelunit').val('');
                  $('#modelprice').val('');
                  $('#modelnumber').val('');
                  $('#modelsum').val('');
                }
            });

        });

      $('#modelprice').change(function(){
        $('#modelsum').val(parseFloat($('#modelprice').val()) * parseFloat($('#modelnumber').val()));
      });

      $('#modelnumber').change(function(){
        $('#modelsum').val(parseFloat($('#modelprice').val()) * parseFloat($('#modelnumber').val()));
      });

      $('#edits').click(function(){
        way='edit';
        //alert($('#table').bootstrapTable('getSelections')[0].id);
        $('#modelid').val($('#table').bootstrapTable('getSelections')[0].id);
        $('#sale_data').val($('#table').bootstrapTable('getSelections')[0].sale);
        $('#modelspec').val($('#table').bootstrapTable('getSelections')[0].spec);
        $('#modelunit').val($('#table').bootstrapTable('getSelections')[0].unit);
        $('#modelnumber').val($('#table').bootstrapTable('getSelections')[0].number);
        $('#modelprice').val($('#table').bootstrapTable('getSelections')[0].price);
        $('#modelsum').val($('#table').bootstrapTable('getSelections')[0].sum);
        $("#addModal").modal();

      });

      $('#deletes').click(function(){
        way='delete';
        var ids = new Array();
        $.each($('#table').bootstrapTable('getSelections'),function(i,item){
          ids.push(item.id);
        });

        $.ajax({
          type : 'get',
          async : false,
          url :'../changereserve',
          data:{
            way:way,
            saleid:ids
          },
          success : function(json) {
            getdata();
          }
        });
      });

      $('#adds').click(function(){
        way='add';
      });

      $('#smt').click(function(){
        $('#summary').val($('#summaryinput').val());
        $('#user').val($('#userinput').val());
        $('#pay').val($('#payinput').val());
      });

      $("#data_1 .input-group.date").datepicker({todayBtn:"linked",keyboardNavigation:!1,forceParse:!1,calendarWeeks:!0,autoclose:!0});
      $('#selectorderdate').change(function(){

        $('#orderdate').val($('#selectorderdate').val());

      });

    });

    window.operateEvents = {

        'click .edit': function (e, value, row, index) {
          way='edit';
          //alert($('#table').bootstrapTable('getSelections')[0].id);

          $('#modelid').val(row.id);
          $('#sale_data').val(row.sale);
          $('#modelspec').val(row.spec);
          $('#modelunit').val(row.unit);
          $('#modelnumber').val(row.number);
          $('#modelprice').val(row.price);
          $('#modelsum').val(row.sum);
          $("#addModal").modal();
        },
        'click .remove': function (e, value, row, index) {
          way='delete';
          $.ajax({
            type : 'get',
            async : false,
            url :'../changereserve',
            data:{
              way:way,
              saleid:row.id
            },
            success : function(json) {
              getdata();
            }
          });

        }
    };

    function operateFormatter(value, row, index) {
        return [
            '<a class="edit" href="javascript:void(0)" title="编辑">',
            '<i class="fa fa-pencil"></i>',
            '</a>&nbsp;  ',
            '<a class="remove" href="javascript:void(0)" title="删除">',
            '<i class="fa fa-trash"></i>',
            '</a>'
        ].join('');
    }

  function getdata(){
    var tablejson;
    $.ajax({
      async : false,
      url : "../getdata",
      type : "GET",
      dataType : 'json',
      timeout : 5000,
      data:{
        saleid:$('#saleid').val()
      },
      success : function(jsonstr) {// 客户端jquery预先定义好的callback函数,成功获取跨域服务器上的json数据后,会动态执行这个callback函数
        //alert(jsonstr.price);
        tablejson=jsonstr;
        $('#table').bootstrapTable({
          columns: [{
            checkbox: true
          },{
            field: 'id',
            title: 'id',
            visible:false
          },{
            field: 'sale',
            title: '产品'
          },
            {
              field: 'spec',
              title: '规格'
            },
            {
              field: 'unit',
              title: '单位'
            },
            {
              field: 'price',
              align: 'right',
              title: '成本'
            }, {
              field: 'number',
              align: 'right',
              title: '数量'
            },{
              field: 'sum',
              align: 'right',
              title: '合计'
            },{
              field: 'operate',
              title: '操作',
              align: 'center',
              events: operateEvents,
              formatter: operateFormatter
            }],
          formatLoadingMessage: function(){
            return "";
          },
          data: tablejson
        });

        $('#table').bootstrapTable('load',tablejson);
        var sum=0;
        $.each(jsonstr,function(i,item){
          sum+=parseFloat(item.sum);
        });
        $('#sumspan').text(sum);
        $('#payablespan').text(sum);
        $('#payable').val(sum);

      },
      error : function(xhr) {
      }
    });
  }


</script>
<div class="col-md-12 ibox ibox-content">
  <div class="ibox-content form-horizontal m-t">
    <input type="hidden" id="saleid" value=<%= @sale.id %> >




    </div>

    <div class="hr-line-dashed"></div>
    <div class="example-wrap">

      <div class="example">
        <div class="btn-group hidden-xs" id="exampleToolbar" role="group">
          <button type="button" class="btn btn-outline btn-default" data-toggle="modal" data-target="#addModal" id="adds">
            <i class="fa fa-plus" aria-hidden="true"></i>
          </button>
          <button type="button" class="btn btn-outline btn-default" id="edits">
            <i class="fa fa-edit" aria-hidden="true"></i>
          </button>
          <button type="button" class="btn btn-outline btn-default" id="deletes">
            <i class="fa fa-trash" aria-hidden="true"></i>
          </button>
        </div>
        <table id="table" data-mobile-responsive="true">
        </table>
      </div>
    </div>


  </div>

  <div class="full-height-scroll">
  <div class="table-responsive">
  <table class="table table-striped table-hover">
    <tbody>
    <tr>

      <td class="col-lg-3">
        <div class="form-group">
          <label class="col-sm-4 control-label text-right" style="margin-top: 10px;">经手人：</label>
          <div class="col-sm-8">
            <input class="form-control text-right" id="userinput">
          </div>
        </div>
      </td>
      <td class="col-lg-3">
        <div class="form-group">
          <label class="col-sm-3 control-label" style="margin-top: 10px;">合计：</label>
          <div class="col-sm-7">
            <span class="form-control" id="sumspan" ></span>
          </div>
        </div>
      </td>
      <td class="col-lg-3 text-right">
        <%= form_for(@sale,:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>
            <%= f.hidden_field :name,class: "form-control",id:'name' %>

            <%= f.hidden_field :spec,class: "form-control",id:'spec' %>
            <%= f.hidden_field :unit,class: "form-control",id:'unit' %>
            <%= f.hidden_field :cost,class: "form-control",id:'cost' %>
            <%= f.hidden_field :price,class: "form-control",id:'price' %>


            <%= f.submit '确定',class: "btn btn-w-m btn-primary",id:'smt',style:'margin-top:-15px;' %>
            <% end %>
      </td>


    </tr>
    </tbody>
  </table>
    </div>
    </div>



</div>

<!-- 模态框（Modal） -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">销售单明细</h4>
      </div>
      <div class="modal-body" >
        <div class="form-horizontal m-t">
          <div class="form-group">
            <label class="col-sm-4 control-label">产品名称：</label>
            <div class="col-sm-8">
              <div class="input-group">
                <input type="text" class="form-control" id="raw_data">
                <div class="input-group-btn">
                  <button type="button" class="btn btn-white dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu dropdown-menu-right" role="menu">
                  </ul>
                </div>
                <!-- /btn-group -->
              </div>
            </div>
          </div>
          <input type="hidden" id="modelid">
          <div class="form-group">
            <label class="col-sm-4 control-label">规格：</label>
            <div class="col-sm-8">
              <input readonly="true" class="form-control" id="modelspec">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-4 control-label">单位：</label>
            <div class="col-sm-8">
              <input readonly="true" class="form-control" id="modelunit">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-4 control-label">单价：</label>
            <div class="col-sm-8">
              <input class="form-control" id="modelprice">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-4 control-label">数量：</label>
            <div class="col-sm-8">
              <input class="form-control" id="modelnumber">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-4 control-label">合计：</label>
            <div class="col-sm-8">
              <input readonly="true" class="form-control" id="modelsum">
            </div>
          </div>

        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal" id="modalsubmit">确定</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
<!-- /.modal -->

app/views/sales/edit.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>销售产品定义</h3>
    </div>
    <%= render 'form', sale: @sale %>
  </div>
</div>
<%=render 'layerend' %>

app/views/sales/index.html.erb
<%= render 'layerbegin' %>
<script>
    $(document).ready(function(){

        $('#searchbtn').click(function(){
            window.location.href=window.location.href.split('?')[0]+'?search='+$('#search').val();
        });

        $('#search').val(getUrlParam('search'));

        function getUrlParam(name) {
            var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)"); //构造一个含有目标参数的正则表达式对象
            var r = window.location.search.substr(1).match(reg); //匹配目标参数
            if (r != null) return decodeURI (r[2]); return null; //返回参数值
        }
    });
</script>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h5>销售结算单</h5>
      <div class="ibox-tools col-sm-3" style="margin-top: -5px;">
        <div class="input-group">
          <input type="text" id="search"  class="input-sm form-control"> <span class="input-group-btn">
             <button type="button" id="searchbtn" class="btn btn-sm btn-primary"> 搜索</button> </span>
        </div>
      </div>
    </div>
    <div class="ibox-content">
      <table class="table table-hover table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">订单号</th>
          <th class="text-center">客户</th>
          <th class="text-center">联系方式</th>
          <th class="text-center">客户地址</th>
          <th class="text-center">已付金额</th>
          <th class="text-center">总金额</th>
          <th class="text-center">未结算金额</th>
          <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <% @preorders.each do |preorder| %>
            <tr>
              <td>
                <%= preorder.ordernumber %>
              </td>
              <% customer = nil %>
              <% if preorder.customer_id && preorder.customer_id != 0 %>
              <% customer = Customer.find(preorder.customer_id) %>
                  <% end %>
              <td>
                <% if customer %>
                <%= customer.name %>
                <% end %>
              </td>
              <td>
                <% if customer %>
                    <%= customer.tel %>
                <% end %>
              </td>
              <td>
                <% if customer %>
                    <%= customer.region %>
                <% end %>
              </td>
              <td>
                <%= preorder.pay %>
              </td>
              <td>
                <% sum = preorder.preorderdetails.sum('sum') %>
                <%= sum %>
              </td>
              <td>
                <% pay = 0 %>
                <% if preorder.pay.to_s != '' %>
                    <% pay = preorder.pay %>
                    <% end %>
                <%= sum - pay %>
              </td>
              <td>
                <% newwork = Newwork.find_by_preordernumber(preorder.id) %>
                <% if newwork %>
                <%= link_to '查看',sett_newwork_path(newwork),class:'fa fa-edit' %>&nbsp;
                    <% end %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to "新增",new_preorder_path,class: "btn btn-w-m btn-primary pull-right" %>
      <br/>
      <div class="text-center">
        <%= will_paginate @preorders, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

<%=render 'layerend' %>

app/views/sales/new.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>新增销售产品</h3>
    </div>
    <%= render 'form', sale: @sale %>
  </div>
</div>
<%=render 'layerend' %>